repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: project-template

  # A short description of the repository that will show up on GitHub
  description: CNCF Project Template

  # A URL with more information about the repository
  homepage: https://cncf.io/projects

  # The branch used by default for pull requests and when the repository is cloned/viewed.
  default_branch: main

  # This repository is a template that others can use to start a new repository.
  is_template: true

  # Collaborators: give specific users access to this repository.
  # see /governance/roles.md for details on write access policy
  # note that the permissions below may provide wider access than needed for
  # a specific role, and we trust these individuals to act according to their
  # role. If there are questions, please contact one of the chairs.
collaborators:
  # Chairs and Admin Help
  - username: justaugustus
    permission: admin

  - username: jberkus
    permission: admin

  - username: parispittman
    permission: admin

  - username: idvoretskyi
    permission: admin

  - username: caniszczyk
    permission: admin

  # Contributors
  # all permissions except admin

  - username: carolynvs
    permission: push

  - username: mattklein123
    permission: push

  - username: thisisnotapril
    permission: push

  - username: karenhchu
    permission: push

  - username: dims
    permission: push

  - username: geekygirldawn
    permission: push

  - username: iennae
    permission: push

labels:
  - name: help-wanted
    color: ffff54

# additional colors in this palette:
# 7f0000 , 1e90ff, ffdab9, ff69b4
